// <auto-generated />
using System;
using EF_POO_II.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_POO_II.Migrations
{
    [DbContext(typeof(SistemaVotacionContext))]
    [Migration("20260815150000_AddChatYRelacionVotoActa")]
    partial class AddChatYRelacionVotoActa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_POO_II.Models.ChatMensaje", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("Fecha").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("GETDATE()");
                b.Property<string>("Mensaje").IsRequired().HasMaxLength(240).IsUnicode(false).HasColumnType("varchar(240)");
                b.Property<string>("Usuario").IsRequired().HasMaxLength(50).IsUnicode(false).HasColumnType("varchar(50)");
                b.HasKey("Id").HasName("PK_ChatMensajes");
                b.ToTable("ChatMensajes");
            });

            modelBuilder.Entity("EF_POO_II.Models.Voto", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int?>("ActaElectoralId").HasColumnType("int");
                b.Property<int>("CandidatoId").HasColumnType("int");
                b.Property<int>("Cantidad").HasColumnType("int");
                b.Property<DateTime?>("Fecha").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("(getdate())");
                b.HasKey("Id").HasName("PK__Votos__3214EC07B1DB355B");
                b.HasIndex("ActaElectoralId");
                b.HasIndex("CandidatoId");
                b.ToTable("Votos");
            });
#pragma warning restore 612, 618
        }
    }
}
