// <auto-generated />
using System;
using EF_POO_II.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_POO_II.Migrations
{
    [DbContext(typeof(SistemaVotacionContext))]
    [Migration("20260816103000_AddSoftDeleteAsignacionesYPasswordHasher")]
    partial class AddSoftDeleteAsignacionesYPasswordHasher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_POO_II.Models.Candidato", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Nombre").IsRequired().HasMaxLength(100).IsUnicode(false).HasColumnType("varchar(100)");
                b.Property<string>("ImagenUrl").HasMaxLength(300).IsUnicode(false).HasColumnType("varchar(300)");
                b.Property<bool>("IsActivo").HasColumnType("bit");
                b.Property<int>("TotalVotos").HasColumnType("int");
                b.HasKey("Id").HasName("PK__Candidat__3214EC073219DE9E");
                b.ToTable("Candidatos");
            });

            modelBuilder.Entity("EF_POO_II.Models.OperadorMesaAsignacion", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("FechaAsignacion").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("GETDATE()");
                b.Property<DateTime?>("FechaCierre").HasColumnType("datetime");
                b.Property<bool>("IsActiva").HasColumnType("bit");
                b.Property<int>("MesaElectoralId").HasColumnType("int");
                b.Property<string>("Observacion").HasMaxLength(120).IsUnicode(false).HasColumnType("varchar(120)");
                b.Property<int>("UsuarioId").HasColumnType("int");
                b.HasKey("Id").HasName("PK_OperadorMesaAsignaciones");
                b.HasIndex("MesaElectoralId");
                b.HasIndex("UsuarioId");
                b.ToTable("OperadorMesaAsignaciones");
            });

            modelBuilder.Entity("EF_POO_II.Models.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<bool>("IsActivo").HasColumnType("bit");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).IsUnicode(false).HasColumnType("varchar(255)");
                b.Property<int>("RolId").HasColumnType("int");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).IsUnicode(false).HasColumnType("varchar(50)");
                b.HasKey("Id").HasName("PK__Usuarios__3214EC073E252F66");
                b.HasIndex("RolId");
                b.HasIndex(new[] { "Username" }, "UQ__Usuarios__536C85E4BD901214").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("EF_POO_II.Models.OperadorMesaAsignacion", b =>
            {
                b.HasOne("EF_POO_II.Models.MesaElectoral", "MesaElectoral")
                    .WithMany()
                    .HasForeignKey("MesaElectoralId")
                    .IsRequired();

                b.HasOne("EF_POO_II.Models.Usuario", "Usuario")
                    .WithMany("AsignacionesMesa")
                    .HasForeignKey("UsuarioId")
                    .IsRequired();

                b.Navigation("MesaElectoral");
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("EF_POO_II.Models.Usuario", b =>
            {
                b.Navigation("AsignacionesMesa");
            });
#pragma warning restore 612, 618
        }
    }
}
