// <auto-generated />
using System;
using EF_POO_II.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_POO_II.Migrations
{
    [DbContext(typeof(SistemaVotacionContext))]
    [Migration("20260815120000_AddFlujoElectoral")]
    partial class AddFlujoElectoral
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_POO_II.Models.ActaElectoral", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("EleccionId").HasColumnType("int");
                b.Property<string>("Estado").IsRequired().HasMaxLength(20).IsUnicode(false).HasColumnType("varchar(20)");
                b.Property<DateTime>("FechaRegistro").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("GETDATE()");
                b.Property<int>("MesaElectoralId").HasColumnType("int");
                b.Property<string>("Observaciones").HasMaxLength(250).IsUnicode(false).HasColumnType("varchar(250)");
                b.Property<string>("UsuarioRegistro").IsRequired().HasMaxLength(50).IsUnicode(false).HasColumnType("varchar(50)");
                b.HasKey("Id").HasName("PK_ActasElectorales");
                b.HasIndex("EleccionId");
                b.HasIndex("MesaElectoralId");
                b.ToTable("ActasElectorales");
            });

            modelBuilder.Entity("EF_POO_II.Models.Auditoria", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Accion").IsRequired().HasMaxLength(80).IsUnicode(false).HasColumnType("varchar(80)");
                b.Property<string>("Descripcion").IsRequired().HasMaxLength(300).IsUnicode(false).HasColumnType("varchar(300)");
                b.Property<DateTime>("Fecha").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("GETDATE()");
                b.Property<string>("TablaAfectada").IsRequired().HasMaxLength(80).IsUnicode(false).HasColumnType("varchar(80)");
                b.Property<string>("Usuario").IsRequired().HasMaxLength(50).IsUnicode(false).HasColumnType("varchar(50)");
                b.HasKey("Id").HasName("PK_Auditorias");
                b.ToTable("Auditorias");
            });

            modelBuilder.Entity("EF_POO_II.Models.Candidato", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ImagenUrl").HasMaxLength(300).IsUnicode(false).HasColumnType("varchar(300)");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(100).IsUnicode(false).HasColumnType("varchar(100)");
                b.Property<int>("TotalVotos").HasColumnType("int");
                b.HasKey("Id").HasName("PK__Candidat__3214EC073219DE9E");
                b.ToTable("Candidatos");
            });

            modelBuilder.Entity("EF_POO_II.Models.DetalleActa", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("ActaElectoralId").HasColumnType("int");
                b.Property<int>("CandidatoId").HasColumnType("int");
                b.Property<int>("Votos").HasColumnType("int");
                b.HasKey("Id").HasName("PK_DetalleActas");
                b.HasIndex("ActaElectoralId");
                b.HasIndex("CandidatoId");
                b.ToTable("DetalleActas");
            });

            modelBuilder.Entity("EF_POO_II.Models.Eleccion", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Estado").IsRequired().HasMaxLength(20).IsUnicode(false).HasColumnType("varchar(20)");
                b.Property<DateTime>("FechaFin").HasColumnType("datetime");
                b.Property<DateTime>("FechaInicio").HasColumnType("datetime");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(120).IsUnicode(false).HasColumnType("varchar(120)");
                b.HasKey("Id").HasName("PK_Elecciones");
                b.ToTable("Elecciones");
            });

            modelBuilder.Entity("EF_POO_II.Models.MesaElectoral", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CodigoMesa").IsRequired().HasMaxLength(20).IsUnicode(false).HasColumnType("varchar(20)");
                b.Property<string>("Distrito").IsRequired().HasMaxLength(80).IsUnicode(false).HasColumnType("varchar(80)");
                b.Property<string>("Estado").IsRequired().HasMaxLength(20).IsUnicode(false).HasColumnType("varchar(20)");
                b.Property<string>("LocalVotacion").IsRequired().HasMaxLength(120).IsUnicode(false).HasColumnType("varchar(120)");
                b.HasKey("Id").HasName("PK_MesasElectorales");
                b.HasIndex("CodigoMesa").IsUnique();
                b.ToTable("MesasElectorales");
            });

            modelBuilder.Entity("EF_POO_II.Models.ReporteExportado", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("FechaCreacion").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("GETDATE()");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(150).IsUnicode(false).HasColumnType("varchar(150)");
                b.Property<string>("RutaGuardado").IsRequired().HasMaxLength(300).IsUnicode(false).HasColumnType("varchar(300)");
                b.HasKey("Id").HasName("PK_ReportesExportados");
                b.ToTable("ReportesExportados");
            });

            modelBuilder.Entity("EF_POO_II.Models.Role", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Nombre").IsRequired().HasMaxLength(50).IsUnicode(false).HasColumnType("varchar(50)");
                b.HasKey("Id").HasName("PK__Roles__3214EC07165DD0FC");
                b.ToTable("Roles");
            });

            modelBuilder.Entity("EF_POO_II.Models.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).IsUnicode(false).HasColumnType("varchar(255)");
                b.Property<int>("RolId").HasColumnType("int");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).IsUnicode(false).HasColumnType("varchar(50)");
                b.HasKey("Id").HasName("PK__Usuarios__3214EC073E252F66");
                b.HasIndex("RolId");
                b.HasIndex(new[] { "Username" }, "UQ__Usuarios__536C85E4BD901214").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("EF_POO_II.Models.Voto", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("CandidatoId").HasColumnType("int");
                b.Property<int>("Cantidad").HasColumnType("int");
                b.Property<DateTime?>("Fecha").ValueGeneratedOnAdd().HasColumnType("datetime").HasDefaultValueSql("(getdate())");
                b.HasKey("Id").HasName("PK__Votos__3214EC07B1DB355B");
                b.HasIndex("CandidatoId");
                b.ToTable("Votos");
            });

            modelBuilder.Entity("EF_POO_II.Models.ActaElectoral", b =>
            {
                b.HasOne("EF_POO_II.Models.Eleccion", "Eleccion").WithMany("Actas").HasForeignKey("EleccionId").IsRequired();
                b.HasOne("EF_POO_II.Models.MesaElectoral", "MesaElectoral").WithMany("Actas").HasForeignKey("MesaElectoralId").IsRequired();
                b.Navigation("Eleccion");
                b.Navigation("MesaElectoral");
            });

            modelBuilder.Entity("EF_POO_II.Models.DetalleActa", b =>
            {
                b.HasOne("EF_POO_II.Models.ActaElectoral", "ActaElectoral").WithMany("Detalles").HasForeignKey("ActaElectoralId").IsRequired().OnDelete(DeleteBehavior.Cascade);
                b.HasOne("EF_POO_II.Models.Candidato", "Candidato").WithMany().HasForeignKey("CandidatoId").IsRequired();
                b.Navigation("ActaElectoral");
                b.Navigation("Candidato");
            });

            modelBuilder.Entity("EF_POO_II.Models.Usuario", b =>
            {
                b.HasOne("EF_POO_II.Models.Role", "Rol").WithMany("Usuarios").HasForeignKey("RolId").IsRequired().HasConstraintName("FK__Usuarios__RolId__4D94879B");
                b.Navigation("Rol");
            });

            modelBuilder.Entity("EF_POO_II.Models.Voto", b =>
            {
                b.HasOne("EF_POO_II.Models.Candidato", "Candidato").WithMany("Votos").HasForeignKey("CandidatoId").IsRequired().HasConstraintName("FK__Votos__Candidato__534D60F1");
                b.Navigation("Candidato");
            });

            modelBuilder.Entity("EF_POO_II.Models.ActaElectoral", b => b.Navigation("Detalles"));
            modelBuilder.Entity("EF_POO_II.Models.Candidato", b => b.Navigation("Votos"));
            modelBuilder.Entity("EF_POO_II.Models.Eleccion", b => b.Navigation("Actas"));
            modelBuilder.Entity("EF_POO_II.Models.MesaElectoral", b => b.Navigation("Actas"));
            modelBuilder.Entity("EF_POO_II.Models.Role", b => b.Navigation("Usuarios"));
#pragma warning restore 612, 618
        }
    }
}
