// <auto-generated />
using EF_POO_II.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EF_POO_II.Migrations
{
    [DbContext(typeof(SistemaVotacionContext))]
    [Migration("20260816113000_AdjustActaPendingVotesProcedure")]
    partial class AdjustActaPendingVotesProcedure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
