// <auto-generated />
using System;
using EF_POO_II.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_POO_II.Migrations
{
    [DbContext(typeof(SistemaVotacionContext))]
    [Migration("20260815133000_AddAsignacionMesaOperador")]
    partial class AddAsignacionMesaOperador
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_POO_II.Models.MesaElectoral", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CodigoMesa").IsRequired().HasMaxLength(20).IsUnicode(false).HasColumnType("varchar(20)");
                b.Property<string>("Distrito").IsRequired().HasMaxLength(80).IsUnicode(false).HasColumnType("varchar(80)");
                b.Property<string>("Estado").IsRequired().HasMaxLength(20).IsUnicode(false).HasColumnType("varchar(20)");
                b.Property<string>("LocalVotacion").IsRequired().HasMaxLength(120).IsUnicode(false).HasColumnType("varchar(120)");
                b.Property<int?>("UsuarioId").HasColumnType("int");
                b.HasKey("Id").HasName("PK_MesasElectorales");
                b.HasIndex("CodigoMesa").IsUnique();
                b.HasIndex("UsuarioId");
                b.ToTable("MesasElectorales");
            });
#pragma warning restore 612, 618
        }
    }
}
